name: Send Email with mutt

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository (optional, if you need access to the repo's files)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install mutt
      - name: Install mutt
        run: sudo apt-get update && sudo apt-get install -y mutt

      # 3. Send email using mutt
      - name: Send email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: xielk@yeah.net,5817253@qq.com
          EMAIL_SUBJECT: Cloudflare Traffic Report for the Last 30 Days
          EMAIL_BODY: |
            Hi,

            Here is the Cloudflare traffic report for the zone ID a768a88b8f71866844da6c81b533ba9c for the last 30 days:

            - Total Bandwidth: ${{ env.BANDWIDTH_TB }} TB
            - Total Requests: ${{ env.REQUESTS }}

            Best regards,
            Cloudflare Monitoring
        run: |
          echo "$EMAIL_BODY" | mutt -s "$EMAIL_SUBJECT" \
              -e "set smtp_url=smtp://$EMAIL_ADDRESS:$EMAIL_PASSWORD@smtp.office365.com:587/" \
              -e "set smtp_authenticators=login" \
              -e "set smtp_use_starttls=yes" \
              -e "set ssl_force_tls=yes" \
              "$EMAIL_TO"
