name: Cloudflare Traffic Report

on:
  workflow_dispatch:

jobs:
  fetch-and-email:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 获取 Cloudflare 流量数据的步骤（请根据你的实际情况调整此步骤）
      - name: Fetch Cloudflare Traffic Data
        id: fetch-data
        run: |
          # 模拟获取带宽和请求数量的逻辑
          # 你需要用实际的 API 调用替换以下内容
          BANDWIDTH_BYTES=104857600  # 模拟的带宽数据，单位是 Bytes
          REQUESTS=1500000  # 模拟的请求数量

          # 计算带宽（TB）
          BANDWIDTH_TB=$(echo "scale=10; $BANDWIDTH_BYTES / 1099511627776" | bc)

          # 设置环境变量
          echo "BANDWIDTH_TB=${BANDWIDTH_TB}" >> $GITHUB_ENV
          echo "REQUESTS=${REQUESTS}" >> $GITHUB_ENV

      # 3. 发送邮件
      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.office365.com
          smtp-port: 465
          smtp-secure: true
          from-email: ${{ secrets.EMAIL_ADDRESS }}
          to-email: |
            xielk@yeah.net
            5817253@qq.com
          username: ${{ secrets.EMAIL_ADDRESS }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Cloudflare Traffic Report for the Last 30 Days
          body: |
            Hi,

            Here is the Cloudflare traffic report for the zone ID a768a88b8f71866844da6c81b533ba9c for the last 30 days:

            - Total Bandwidth: ${{ env.BANDWIDTH_TB }} TB
            - Total Requests: ${{ env.REQUESTS }}

            Best regards,
            Cloudflare Monitoring
          html: |
            <h1>Cloudflare Traffic Report</h1>
            <p>Hi,</p>
            <p>Here is the Cloudflare traffic report for the zone ID a768a88b8f71866844da6c81b533ba9c for the last 30 days:</p>
            <ul>
              <li>Total Bandwidth: ${{ env.BANDWIDTH_TB }} TB</li>
              <li>Total Requests: ${{ env.REQUESTS }}</li>
            </ul>
            <p>Best regards,</p>
            <p>Cloudflare Monitoring</p>
