name: Send Email with msmtp and sendmail

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository (optional, if you need access to the repo's files)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install msmtp and sendmail
      - name: Install msmtp and sendmail
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp msmtp-mta

      # 3. Configure msmtp
      - name: Configure msmtp
        run: |
          echo "defaults" > ~/.msmtprc
          echo "auth login" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
          echo "host smtp.office365.com" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "user ${{ secrets.EMAIL_ADDRESS }}" >> ~/.msmtprc
          echo "password ${{ secrets.EMAIL_PASSWORD }}" >> ~/.msmtprc
          echo "from ${{ secrets.EMAIL_ADDRESS }}" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

      # 4. Send email using sendmail and msmtp
      - name: Send email
        env:
          EMAIL_TO: xielk@yeah.net,5817253@qq.com
          EMAIL_SUBJECT: Cloudflare Traffic Report for the Last 30 Days
          EMAIL_BODY: |
            Hi,

            Here is the Cloudflare traffic report for the zone ID a768a88b8f71866844da6c81b533ba9c for the last 30 days:

            - Total Bandwidth: ${{ env.BANDWIDTH_TB }} TB
            - Total Requests: ${{ env.REQUESTS }}

            Best regards,
            Cloudflare Monitoring
        run: |
          echo -e "Subject: $EMAIL_SUBJECT\nTo: $EMAIL_TO\n\n$EMAIL_BODY" | sendmail -t
