name: Send Cloudflare Analytics Notification

on:
  workflow_dispatch:  # 手动触发

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 你可以根据需要修改 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        ZONE_ID: ${{ secrets.ZONE_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        OPEN_ID: ${{ secrets.OPEN_ID }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      run: python report_cdn.py  # 替换为你的 Python 脚本名
