name: Cloudflare Traffic Report

on:
  workflow_dispatch:

jobs:
  fetch-and-email:
    runs-on: ubuntu-latest

    steps:
      # 1. 获取 Cloudflare 流量数据的步骤（请根据你的实际情况调整此步骤）
      - name: Fetch Cloudflare Traffic Data
        id: fetch-data
        run: |
          # 模拟获取带宽和请求数量的逻辑
          # 你需要用实际的 API 调用替换以下内容
          BANDWIDTH_BYTES=104857600  # 模拟的带宽数据，单位是 Bytes
          REQUESTS=1500000  # 模拟的请求数量

          # 计算带宽（TB）
          BANDWIDTH_TB=$(echo "scale=10; $BANDWIDTH_BYTES / 1099511627776" | bc)

          echo "BANDWIDTH_TB=${BANDWIDTH_TB}" >> $GITHUB_ENV
          echo "REQUESTS=${REQUESTS}" >> $GITHUB_ENV

      # 2. 运行 Python 脚本发送邮件
      - name: Send traffic report via email
        run: |
          python3 send_email.py

      # 3. 调试 SMTP 连接（可选）
      - name: Test SMTP connection
        run: |
          echo | openssl s_client -connect smtp.office365.com:587 -starttls smtp

      # 4. 启用调试日志（可选）
      - name: Enable debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
