name: Send Email with mailutils

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository (optional, if you need access to the repo's files)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install mailutils
      - name: Install mailutils
        run: sudo apt-get update && sudo apt-get install -y mailutils

      # 3. Send email using mailutils
      - name: Send email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_TO: xielk@yeah.net,5817253@qq.com
          EMAIL_SUBJECT: Cloudflare Traffic Report for the Last 30 Days
          EMAIL_BODY: |
            Hi,

            Here is the Cloudflare traffic report for the zone ID a768a88b8f71866844da6c81b533ba9c for the last 30 days:

            - Total Bandwidth: ${{ env.BANDWIDTH_TB }} TB
            - Total Requests: ${{ env.REQUESTS }}

            Best regards,
            Cloudflare Monitoring
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          echo "$EMAIL_BODY" | mail -s "$EMAIL_SUBJECT" \
              -S smtp=smtp.office365.com \
              -S smtp-auth=login \
              -S smtp-auth-user="$EMAIL_ADDRESS" \
              -S smtp-auth-password="$EMAIL_PASSWORD" \
              -S smtp-use-starttls \
              -S smtp-port=587 \
              "$EMAIL_TO"
