name: Send Email

on:
  workflow_dispatch:  # 手动触发工作流程

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp-mail.outlook.com  # Hotmail 的 SMTP 服务器
        server_port: 587  # 使用 TLS
        username: ${{ secrets.EMAIL_ADDRESS }}  # 你的 Hotmail 地址
        password: ${{ secrets.EMAIL_PASSWORD }}  # 你的 Hotmail 密码或应用专用密码
        subject: 'GitHub Actions Email Notification'
        body: 'This is a test email sent from GitHub Actions!'
        to: recipient@example.com  # 收件人邮箱
        from: ${{ secrets.EMAIL_ADDRESS }}  # 发件人邮箱
        secure: true  # 使用 SSL/TLS
