name: Send Email

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com  # 你的 SMTP 服务器地址
        server_port: 465  # SMTP 服务器端口
        username: ${{ secrets.EMAIL_ADDRESS }}  # 你的邮箱
        password: ${{ secrets.EMAIL_PASSWORD }}  # 你的邮箱密码
        subject: 'GitHub Actions Email Notification'
        body: 'This is a test email sent from GitHub Actions!'
        to: recipient@example.com  # 收件人邮箱
        from: ${{ secrets.EMAIL_ADDRESS }}  # 发件人邮箱
        secure: true  # 使用 SSL/TLS 加密
