
name: Send Email

on:
  workflow_dispatch:


jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          connection_url: smtp://${{secrets.EMAIL_ADDRESS}}:${{secrets.EMAIL_PASSWORD}}@smtp.office365.com:587
          server_address: smtp.office365.com
          server_port: 587
          secure: false
          username: ${{secrets.EMAIL_ADDRESS}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Github Actions job result
          to: xielk@yeah.net,5817253@qq.com
          from: Cloudflare CDN ${{secrets.EMAIL_ADDRESS}}
          body: Build job of completed successfully!
          
          cc: 5817253@qq.com
          bcc: 5817253@qq.com
          reply_to: xielk@yeah.net
          in_reply_to: <5817253@qq.com>
          ignore_cert: true
          convert_markdown: true
          attachments: send_email.py,README.md
          priority: low
