name: Send Email using swaks

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install swaks
      - name: Install swaks
        run: sudo apt-get update && sudo apt-get install -y swaks

      # Step 2: Send email using swaks
      - name: Send email
        run: |
          swaks --to xielk@yeah.net \
                --from ${{ secrets.EMAIL_ADDRESS }} \
                --server smtp.office365.com \
                --auth PLAIN \
                --auth-user ${{ secrets.EMAIL_ADDRESS }} \
                --auth-password ${{ secrets.EMAIL_PASSWORD }} \
                --tls --port 587
