name: Check SMTP Port and Send Email

on:
  workflow_dispatch:

jobs:
  check_smtp_port:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if SMTP port 465 is open
      run: |
        nc -zv smtp.office365.com 465 && echo "smtp port open" || echo "smtp port closed"
    
    - name: Send mail if port is open
      if: success()  # 仅在上一步检查成功时才发送邮件
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.office365.com
        server_port: 465
        secure: true  # 使用 SSL 加密连接

        # User credentials from GitHub Secrets
        username: ${{ secrets.EMAIL_ADDRESS }}
        password: ${{ secrets.EMAIL_PASSWORD }}

        # Email subject
        subject: '${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}'

        # Email body as text
        body: |
          Hello,

          The ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}.

        # Recipients (comma-separated string)
        to: xielk@yeah.net,5817253@qq.com

        # From email address
        from: XYZ <${{ secrets.EMAIL_ADDRESS }}>
