
name: Send Email

on:
  workflow_dispatch:


jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dante-evans/send-email@v1
        with:
          smtp-server: smtp.office365.com
          smtp-port: 587
          smtp-secure: false
          from-email: ${{ secrets.EMAIL_ADDRESS }}
          to-email: xielk@yeah.net
          username: ${{ secrets.EMAIL_ADDRESS }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
            <h1>This is a test email</h1>
            <p>Test Paragraph</p>

